// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: event.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createEvent = `-- name: CreateEvent :execresult
INSERT INTO Event (id_user, title, event_time)
VALUES (?, ?, ?)
`

type CreateEventParams struct {
	IDUser    int64     `json:"id_user"`
	Title     string    `json:"title"`
	EventTime time.Time `json:"event_time"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEvent, arg.IDUser, arg.Title, arg.EventTime)
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM Event
WHERE id = ?
`

func (q *Queries) DeleteEvent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, id)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, id_user, title, event_time
FROM Event
WHERE id = ? LIMIT 1
`

func (q *Queries) GetEvent(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.IDUser,
		&i.Title,
		&i.EventTime,
	)
	return i, err
}

const listEvent = `-- name: ListEvent :many
SELECT id, id_user, title, event_time
FROM Event
ORDER BY id
`

func (q *Queries) ListEvent(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.IDUser,
			&i.Title,
			&i.EventTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
